<a href="https://colab.research.google.com/github/yong2691/DataScience/blob/main/03_%ED%85%8C%EC%9D%B4%EB%B8%94%ED%98%95_%EC%88%98%EC%B9%98_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

numbers = np.array(range(1,11), copy=True) #array는 배열을 만드는 것
numbers
numbers.dtype

dtype('int64')

ones() -> 1,  zeros() -> 0,  empty() -> 아직 생성되지 않은 엔트리로 구성
https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array

In [ ]:
#아직 생성되지 않은 엔트리로 구성된 배열을 1로 채움 
ones = np.ones([2,4], dtype=np.int64) #2행 4열, 정수
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
#아직 생성되지 않은 엔트리로 구성된 배열을 1로 채움 
ones = np.ones([2,4], dtype=np.float64) #2행 4열, 소수
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열을 0으로 채움
zeros = np.zeros([2,4], dtype=np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 아직 생성되지 않은 엔트리로 구성된 배열을 0으로 채움
empty = np.empty([2,4], dtype=np.float64)
empty

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

데이터 확인하기

In [ ]:
ones.shape #몇행 몇열 인지 확인

(2, 4)

In [ ]:
ones.ndim

2

In [ ]:
ones.dtype #data type 확인

dtype('int64')

In [ ]:
numbers.dtype

dtype('int64')

arange(start, stop, step, dtype=None) 일정 간격으로 배열 생성하는 함수

In [ ]:
np_numbers = np.arange(2,5,0.25)
np_numbers

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

astype(dtype, casting="unsafe", copy=True) 아이템의 타입 변경해 주는 함수

In [ ]:
np_numbers.dtype

dtype('int64')

In [ ]:
np_numbers = np_numbers.astype(np.int)
np_numbers

array([2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

reshape(d0,d1, ...) 대상 배열의 모양을 바꿔주는 함수

In [ ]:
# 몇 가지 S&P 주식 기호들
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap #U4 는 4글자 유니코드 = 유니코드는 숫자로 변환 가능.


array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [ ]:
sap.shape #8행 0열? row(행)만 8개 존재 = 1차원이라는 뜻

(8,)

In [ ]:
sap2d = sap.reshape(2,4) #2차원
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [ ]:
sap3d = sap.reshape(2,2,2) #3차원함수
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [ ]:
# 기존 배열과 새로운 배열의 아이템의 갯수는 항상 동일 해야 함
# numpy 보존의 법칙 성립
sap3d = sap.reshape (2,2,2) # 3차원으로 변경
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [ ]:
sap3d[0] # 1차원

array([['MMM', 'ABT'],
       ['ABBV', 'ACN']], dtype='<U4')

In [ ]:
sap3d[1]

array([['ACE', 'ATVI'],
       ['ADBE', 'ADT']], dtype='<U4')

In [ ]:
sap3d[2]

IndexError: ignored

In [ ]:
sap3d.dtype

dtype('<U4')

In [ ]:
#sap3d 3차원배열의 shape 확인
sap3d.shape

(2, 2, 2)

데이터 클리닝(data cleaning)을 위해 사용 되는 boolean indexing

In [ ]:
 # 절대 음수 값이 와서는 안되는 데이터셋
 dirty = np.array([9,4,1,-0.01,-0.02,-0.001])
 whos_dirty = dirty < 0
 whos_dirty

array([False, False, False,  True,  True,  True])

In [ ]:
#모든 음수값을 0으로 바꿈
dirty[whos_dirty] = 0 
dirty

array([9., 4., 1., 0., 0., 0.])

논리 연산자 | or, & and, - not 결합하여 boolean indexing 사용


In [ ]:
linear = np.arange(-1,1.1,0.2)
linear

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01,  1.00000000e+00])

In [ ]:
# -0.5 ~ 0.5 사이의 값만 -> 0으로 변경하고 싶음
whos_linear = (linear <= 0.5) & (linear >= -0.5)
whos_linear

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False])

In [ ]:
linear[whos_linear] = 0
linear

array([-1. , -0.8, -0.6,  0. ,  0. ,  0. ,  0. ,  0. ,  0.6,  0.8,  1. ])

스마트 인덱싱

In [ ]:
# S&P 리스트에서 두번쨰, 세번째, 마지막 주식 기호를 추출
sap[[1,2,-1]]

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [ ]:
sap2d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

In [ ]:
sap2d[:,[1]] #2차원

array([[['ABBV', 'ACN']],

       [['ADBE', 'ADT']]], dtype='<U4')

In [ ]:
sap2d[:,1] #1차원

array([['ABBV', 'ACN'],
       ['ADBE', 'ADT']], dtype='<U4')

차원만 같다면 numpy에서는 사칙연산 가능 (그낭 더하기) -> 브로드캐스팅

In [ ]:
a = np.arange(4)
b = np.arange(1,5)

print(a) # 1행4열
print(b) # 1행4열

[0 1 2 3]
[1 2 3 4]


In [ ]:
a+b  # 4행?

array([1, 3, 5, 7])

In [ ]:
a*5 # 스칼라값을 구할 수 있다.

array([ 0,  5, 10, 15])

In [ ]:
noise = np.eye(4)
noise

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
noise = np.random.random([4,4])
noise

array([[0.28767083, 0.0097111 , 0.52093853, 0.65625381],
       [0.95354988, 0.99245923, 0.98030904, 0.12903178],
       [0.33711459, 0.3675248 , 0.12272507, 0.59869749],
       [0.59968013, 0.01967265, 0.67421566, 0.71014323]])

In [ ]:
noise = np.eye(4) + np.random.random([4,])
noise

array([[1.28543221, 0.42643535, 0.86517097, 0.15117719],
       [0.28543221, 1.42643535, 0.86517097, 0.15117719],
       [0.28543221, 0.42643535, 1.86517097, 0.15117719],
       [0.28543221, 0.42643535, 0.86517097, 1.15117719]])